import { useMemo } from "react";
import {
    Bike, Building2, CheckCircle2, CircleDollarSign, HandCoins, Truck, Wallet,
} from "lucide-react";
import {
    calculateFinancialSummary, getDeliveryAccountability, getDriverFinancials,
    getStationPerformance,
} from "../../../data/mockData";
import { formatCurrency } from "../../../utils/dataHelpers";

const Kpi = ({
    icon: Icon, iconBg, label, value, sub,
}: {
    icon: React.ComponentType<{ className?: string }>;
    iconBg: string; label: string; value: string; sub: string;
}) => (
    <div className="rounded-2xl border border-[#e3e3e3] bg-white p-5 shadow-sm">
        <div className="flex items-start justify-between">
            <p className="text-[11px] font-semibold uppercase tracking-wider text-neutral-400">{label}</p>
            <div className={`flex h-9 w-9 items-center justify-center rounded-xl ${iconBg}`}>
                <Icon className="h-[18px] w-[18px]" />
            </div>
        </div>
        <p className="mt-1 text-2xl font-extrabold tracking-tight text-neutral-900">{value}</p>
        <p className="mt-1.5 text-xs text-neutral-500">{sub}</p>
    </div>
);

const SectionCard = ({
    title, sub, children,
}: { title: string; sub: string; children: React.ReactNode }) => (
    <div className="overflow-hidden rounded-2xl border border-[#e3e3e3] bg-white shadow-sm">
        <div className="border-b border-[#ececec] px-5 py-4">
            <h2 className="text-sm font-bold text-neutral-800">{title}</h2>
            <p className="mt-0.5 text-xs text-[#8a8a8a]">{sub}</p>
        </div>
        {children}
    </div>
);

const payBadge = (status: string) =>
    status === "paid"
        ? "bg-green-50 text-green-700"
        : status === "partial"
            ? "bg-amber-50 text-amber-700"
            : "bg-red-50 text-red-600";

export const DeliveryIncome = (): JSX.Element => {
    const finance = useMemo(() => calculateFinancialSummary(), []);
    const stations = useMemo(
        () => [...getStationPerformance()].sort((a, b) => b.deliveryEarnings - a.deliveryEarnings),
        []
    );
    const riders = useMemo(
        () => [...getDriverFinancials()].sort((a, b) => b.totalEarned - a.totalEarned),
        []
    );
    const records = useMemo(() => getDeliveryAccountability(), []);

    const netIncome = finance.totalDeliveryEarnings + finance.totalItemCollections - finance.pendingPayments;

    return (
        <div className="w-full">
            <div className="mx-auto w-full max-w-7xl px-4 py-6 sm:px-6 lg:px-8 lg:py-8">

                {/* ── Header ── */}
                <div className="mb-6">
                    <h1 className="text-2xl font-bold tracking-tight text-neutral-900">Delivery Income</h1>
                    <p className="mt-1 text-sm text-[#7d7d7d]">
                        Income generated by Delivery Hub operations — delivery fees, COD collections, and rider payouts.
                    </p>
                </div>

                {/* ── KPI row ── */}
                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
                    <Kpi
                        icon={Truck} iconBg="bg-orange-50 text-[#ea690c]"
                        label="Delivery Fees" value={formatCurrency(finance.totalDeliveryEarnings)}
                        sub="Fees collected on completed deliveries"
                    />
                    <Kpi
                        icon={HandCoins} iconBg="bg-blue-50 text-[#1e40af]"
                        label="COD Collections" value={formatCurrency(finance.totalItemCollections)}
                        sub="Item values collected on delivery"
                    />
                    <Kpi
                        icon={Wallet} iconBg="bg-red-50 text-red-500"
                        label="Rider Payouts Owed" value={formatCurrency(finance.pendingPayments)}
                        sub="Outstanding balances to riders"
                    />
                    <Kpi
                        icon={CircleDollarSign} iconBg="bg-green-50 text-green-600"
                        label="Net Delivery Income" value={formatCurrency(netIncome)}
                        sub="Fees + COD − outstanding payouts"
                    />
                </div>

                <div className="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-2">
                    {/* ── Income by station ── */}
                    <SectionCard title="Income by Station" sub="Delivery earnings generated per station">
                        <div className="overflow-x-auto">
                            <table className="w-full min-w-[420px] text-sm">
                                <thead>
                                    <tr className="border-b border-neutral-100 text-left text-[11px] uppercase tracking-wider text-neutral-400">
                                        <th className="px-5 py-3 font-semibold">Station</th>
                                        <th className="px-5 py-3 text-right font-semibold">Parcels</th>
                                        <th className="px-5 py-3 text-right font-semibold">Earnings</th>
                                        <th className="px-5 py-3 text-right font-semibold">Payouts Owed</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {stations.map(st => (
                                        <tr key={st.stationId} className="border-b border-neutral-50 last:border-0 hover:bg-neutral-50/60">
                                            <td className="px-5 py-3.5">
                                                <div className="flex items-center gap-2.5">
                                                    <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-orange-50">
                                                        <Building2 className="h-4 w-4 text-[#ea690c]" />
                                                    </div>
                                                    <span className="font-medium text-neutral-800">{st.stationName}</span>
                                                </div>
                                            </td>
                                            <td className="px-5 py-3.5 text-right text-neutral-700">{st.totalParcels}</td>
                                            <td className="px-5 py-3.5 text-right font-semibold text-neutral-900">{formatCurrency(st.deliveryEarnings)}</td>
                                            <td className={`px-5 py-3.5 text-right font-medium ${st.driverPaymentsOwed > 0 ? "text-red-500" : "text-neutral-400"}`}>
                                                {formatCurrency(st.driverPaymentsOwed)}
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    </SectionCard>

                    {/* ── Rider earnings ── */}
                    <SectionCard title="Rider Earnings & Payouts" sub="What riders earned and what is still owed">
                        <div className="overflow-x-auto">
                            <table className="w-full min-w-[460px] text-sm">
                                <thead>
                                    <tr className="border-b border-neutral-100 text-left text-[11px] uppercase tracking-wider text-neutral-400">
                                        <th className="px-5 py-3 font-semibold">Rider</th>
                                        <th className="px-5 py-3 text-right font-semibold">Earned</th>
                                        <th className="px-5 py-3 text-right font-semibold">Outstanding</th>
                                        <th className="px-5 py-3 text-right font-semibold">Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {riders.map(r => (
                                        <tr key={r.driverId} className="border-b border-neutral-50 last:border-0 hover:bg-neutral-50/60">
                                            <td className="px-5 py-3.5">
                                                <div className="flex items-center gap-2.5">
                                                    <div className="flex h-8 w-8 items-center justify-center rounded-full bg-gradient-to-br from-[#ea690c] to-[#c2470a] text-[10px] font-bold text-white">
                                                        {r.driverName.split(" ").map(n => n[0]).join("").toUpperCase().slice(0, 2)}
                                                    </div>
                                                    <div>
                                                        <p className="font-medium text-neutral-800">{r.driverName}</p>
                                                        <p className="flex items-center gap-1 text-[11px] text-neutral-400">
                                                            <Bike className="h-3 w-3" /> {r.deliveriesCompleted} deliveries
                                                        </p>
                                                    </div>
                                                </div>
                                            </td>
                                            <td className="px-5 py-3.5 text-right font-semibold text-neutral-900">{formatCurrency(r.totalEarned)}</td>
                                            <td className={`px-5 py-3.5 text-right font-medium ${r.outstandingBalance > 0 ? "text-red-500" : "text-neutral-400"}`}>
                                                {formatCurrency(r.outstandingBalance)}
                                            </td>
                                            <td className="px-5 py-3.5 text-right">
                                                <span className={`inline-flex rounded-full px-2.5 py-0.5 text-[11px] font-semibold capitalize ${payBadge(r.paymentStatus)}`}>
                                                    {r.paymentStatus}
                                                </span>
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    </SectionCard>
                </div>

                {/* ── Per-parcel income ── */}
                <div className="mt-6">
                    <SectionCard title="Delivered Parcel Income" sub="Income collected on each completed delivery">
                        <div className="overflow-x-auto">
                            <table className="w-full min-w-[640px] text-sm">
                                <thead>
                                    <tr className="border-b border-neutral-100 text-left text-[11px] uppercase tracking-wider text-neutral-400">
                                        <th className="px-5 py-3 font-semibold">Parcel</th>
                                        <th className="px-5 py-3 font-semibold">Recipient</th>
                                        <th className="px-5 py-3 font-semibold">Station</th>
                                        <th className="px-5 py-3 font-semibold">Rider</th>
                                        <th className="px-5 py-3 text-right font-semibold">Delivery Fee</th>
                                        <th className="px-5 py-3 text-right font-semibold">COD Collected</th>
                                        <th className="px-5 py-3 text-right font-semibold">Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {records.map(rec => (
                                        <tr key={rec.parcelId} className="border-b border-neutral-50 last:border-0 hover:bg-neutral-50/60">
                                            <td className="px-5 py-3.5 font-mono text-xs font-semibold text-neutral-700">{rec.parcelId}</td>
                                            <td className="px-5 py-3.5 text-neutral-800">{rec.recipientName}</td>
                                            <td className="px-5 py-3.5 text-neutral-600">{rec.stationName}</td>
                                            <td className="px-5 py-3.5 text-neutral-600">{rec.riderName}</td>
                                            <td className="px-5 py-3.5 text-right font-semibold text-neutral-900">{formatCurrency(rec.deliveryFee)}</td>
                                            <td className="px-5 py-3.5 text-right text-neutral-700">{formatCurrency(rec.itemValueCollected)}</td>
                                            <td className="px-5 py-3.5 text-right">
                                                <span className="inline-flex items-center gap-1 rounded-full bg-green-50 px-2.5 py-0.5 text-[11px] font-semibold capitalize text-green-700">
                                                    <CheckCircle2 className="h-3 w-3" /> {rec.status}
                                                </span>
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    </SectionCard>
                </div>
            </div>
        </div>
    );
};
